### PR TITLE
Attempt using labels for jx 3 pipeline activities

### PR DESCRIPTION
**Pull request by rishka**

### CODE REVIEW

**Comment by jstrachan** [comment]
I guess we could always modify the code to list all activities and look for either format?

**Comment by rishka** [comment]
> I guess we could always modify the code to list all activities and look for either format?

Yea, its possible. I am going to work with this some more, as it unfortunately doesn't fix anything other than the error message in logs. 

I do kind of wonder if it should just be versioned, base it on `lighthouse-version` or something

**Comment by jstrachan** [comment]
this PR tries to be more label agnostic: https://github.com/jenkins-x-plugins/jx-slack/pull/35

**Comment by rishka** [comment]
> this PR tries to be more label agnostic: #35

Tried it out, looks like it works on my side, closing this one

**Pull request closed without merging**
